export const ADD_CASH = 'ADD_CASH';
export const ASYNC_ADD_CASH = 'ASYNC_ADD_CASH';
export const GET_CASH = 'GET_CASH';
export const ASYNC_GET_CASH = "ASYNC_GET_CASH"


export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const ADD_ANY_CUSTOMER = 'ADD_ANY_CUSTOMER';
export const ASYNC_SET_CUSTOMERS = "ASYNC_SET_CUSTOMERS"